#!/bin/sh /etc/rc.common

START=90

LBPANEL_CONFIG="/tmp/LBPanel.conf"

start(){
	. /usr/share/scripts/start-lbpanel.sh ${LBPANEL_CONFIG}
}

stop(){
	killall LBPanel
}

restart(){
	stop
	sleep 2
	start
}

reload(){
	. /usr/share/scripts/lbpanel-uci-config.sh reload ${LBPANEL_CONFIG} &
}

